### PR TITLE
remove dependencies on string,

### PR DESCRIPTION
**Pull request by nolange**
Add a new config MEMBER_AT_REPORTS_DETAIL, disabled
by default.
Enabling this config option will result in extended
messages for out-of-bounds access

should be portable aslong index_t is signed and not
bigger than a longlong

see #16

### CODE REVIEW

**Comment by martinmoene** [comment]
@nolange Thanks for your help. Instead of introducing `span_CONFIG_MEMBER_AT_REPORTS_DETAIL` I've chosen to control this via `span_FEATURE_MEMBER_AT`'s value. I'm also using `long` instead of `long long` for non-MSVC pre-C++11 compilers.

**Comment by nolange** [comment]
Thanks for fixing this that fast. One question though: did you try just using sprintf?
AFAIK, old (MS) compilers don't have snprintf and newer one have a specialization to automatically use a similar function if the the first argument to sprintf is an array.

(I had to mess with workarounds because I used a pointer)

**Comment by martinmoene** [comment]
>One question though: did you try just using sprintf?

It did cross my mind. As the format specifier must adapt based on the availability of `%lli` (and may have to downgrade to `%li)` anyway, I thought it acceptable to also differentiate between the various guises of `printf()`.

If you're happy with the result the PR can be closed.

@nolange , thanks a lot for bringing this up (the dragging of heavy dependencies) and help solve it!
___

In the past I have done embedded programming in x6805 assembly, more recently [on Arduino](https://github.com/MarkMoene/MoonPhaseCalendar) to support my son with a school project and I'm (somewhat) keen to [support embedded use of the *lite* libraries](https://github.com/martinmoene/gsl-lite/issues/87).

**Comment by nolange** [comment]
> As the format specifier must adapt based on the availability of %lli ...
that's completely irrelevant for choosing between s[n]printf, any C99 capable system/clibrary needs to support it. The only unkown is MSVC, there aint any docs online anymore before VS2010, but I believe they supported this specifier for decades.

the only argument against using sprintf would be if some compiler goes crazy with warnings.

**Pull request closed without merging**
